#!/usr/bin/env python3
"""Generate embedded_firmware.cpp/.hpp from firmware files in the ares submodule.

The ares cores need small firmware/database blobs at runtime (system pak
contents). Embedding them in the native library keeps loadSystem(systemId)
asset-free on both platforms — no R.raw resources on Android, no bundle
files on iOS. Everything comes from the ares submodule at build time;
nothing is committed to this repo.

Usage: generate_firmware.py <ares_root> <out_dir>
"""

import sys
from pathlib import Path

# (C symbol, path relative to ares root)
BLOBS = [
    ("SfcIpl",     "mia/Firmware/Super Famicom/ipl.rom"),
    ("SfcBoards",  "mia/Database/Super Famicom Boards.bml"),
    ("GbBootDmg1", "mia/Firmware/Game Boy/boot.dmg-1.rom"),
    ("GbBootCgb1", "mia/Firmware/Game Boy Color/boot.cgb-1.rom"),
    ("MdTmss",     "mia/Firmware/Mega Drive/tmss.rom"),
    ("MdSvp",      "mia/Firmware/Mega Drive/svp.rom"),
    ("WsBoot",     "mia/Firmware/WonderSwan/boot.rom"),
    ("WscBoot",    "mia/Firmware/WonderSwan Color/boot.rom"),
]


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 1

    ares_root = Path(sys.argv[1])
    out_dir = Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)

    hpp = [
        "// Generated by scripts/generate_firmware.py — do not edit.",
        "#pragma once",
        "#include <cstddef>",
        "",
        "namespace EmbeddedFirmware {",
    ]
    cpp = [
        "// Generated by scripts/generate_firmware.py — do not edit.",
        '#include "embedded_firmware.hpp"',
        "",
        "namespace EmbeddedFirmware {",
    ]

    for symbol, rel_path in BLOBS:
        data = (ares_root / rel_path).read_bytes()
        hpp.append(f"extern const unsigned char {symbol}[{len(data)}];")
        hpp.append(f"inline constexpr size_t {symbol}Size = {len(data)};")
        body = ",".join(str(b) for b in data)
        cpp.append(f"extern const unsigned char {symbol}[{len(data)}] = {{{body}}};")

    hpp.append("}")
    cpp.append("}")

    (out_dir / "embedded_firmware.hpp").write_text("\n".join(hpp) + "\n")
    (out_dir / "embedded_firmware.cpp").write_text("\n".join(cpp) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
